version: "2"

services:
  app:
    build: .
    container_name: app.server
    ports:
      - "80:80"
      - "5555:5555"
    volumes:
      - ./:/home/sites/app/
    environment:
      - C_FORCE_ROOT=true
    networks:
      - topline-network
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    container_name: app.postgres
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - postgres-conf:/etc/postgresql
      - postgres-logs:/var/log/postgresql

    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: #
      POSTGRES_DB: #

    networks:
      - lab-network

volumes:
  postgres-data:
  postgres-conf:
  postgres-logs:
  topline-var:

networks:
  lab-network:
    driver: bridge