version: "3"

services:
  app:
    build: .
    container_name: app.backend
    volumes:
      - ./:/home/app/
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    container_name: app.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - postgres-conf:/etc/postgresql
      - postgres-logs:/var/log/postgresql

    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: testpassword # CHANGE_ME
      POSTGRES_DB: app

    networks:
      - app-network

  nginx:
    image: nginx
    restart: always
    container_name: app.nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  postgres-data:
  postgres-conf:
  postgres-logs:

networks:
  app-network:
    driver: bridge
